
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
# again we chose deploy cause just copying instructor and seems like a good name
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t graphneenja/next-js-app
    - run: echo "$${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push graphneenja/next-js-app:v14

# here we go