
name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
    # set up node env before doing anything
      uses: actions/setup-node@v4
      with:
      # set up w/several node versions
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "my name for tshooting or whatever - installing dependencies"
    - run: npm i
    - name: 'my stuff is building'
    - run: npm run build
    # from the original copy
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
  # copy/pasted from the entire build block above
  # name this job 'unit-tests'
  unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
#
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
    # set up node env before doing anything
      uses: actions/setup-node@v4
      with:
      # set up w/several node versions
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "my name for tshooting or whatever - installing dependencies"
    - run: npm i
    - name: 'lets run test this time'
    - run: npm run test
    
# test it